config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tickets, only: [:create]
    end
  end

  resources :tickets, only: [:index, :show]
  root to: "tickets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket

  def full_address
    [self.street, self.city, self.state, self.zip].reject(&:blank?).join(", ")
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator

  validates_presence_of :original_json

  before_create :extract_fields_from_original_json
  after_commit :auto_create_excavator, on: [:create]

  def well_known_shape
    if self.well_known_text
      shape = self.well_known_text.split("((").first.strip
      str = self.well_known_text.split("((").last.sub("))", "")
      point_str_arr = str.split(/\s*,\s*/)

      points = point_str_arr.collect{|point_str|
        numbers = point_str.split(/\s+/)
        {
          lat: numbers[1].to_f,
          lng: numbers[0].to_f
        }
      }

      {
        shape: shape,
        points: points
      }
    end
  end

  private

  def extract_fields_from_original_json
    self.request_number = self.original_json["RequestNumber"]
    self.sequence_number = self.original_json["SequenceNumber"]
    self.request_type = self.original_json["RequestType"]
    self.response_due_date_time = self.original_json["DateTimes"]
                                      .try(:[], "ResponseDueDateTime")
    self.primary_service_area_code = self.original_json["ServiceArea"]
                                         .try(:[], "PrimaryServiceAreaCode")
                                         .try(:[], "SACode")
    self.additional_service_area_codes = self.original_json["ServiceArea"]
                                             .try(:[], "AdditionalServiceAreaCodes")
                                             .try(:[], "SACode")
    self.well_known_text = self.original_json["ExcavationInfo"]
                               .try(:[], "DigsiteInfo")
                               .try(:[], "WellKnownText")
  end

  def auto_create_excavator
    excavator_attrs = {}
    excavator_json = self.original_json["Excavator"] || {}
    excavator_attrs[:company_name] = excavator_json["CompanyName"]
    excavator_attrs[:street] = excavator_json["Address"]
    excavator_attrs[:city] = excavator_json["City"]
    excavator_attrs[:state] = excavator_json["State"]
    excavator_attrs[:zip] = excavator_json["Zip"]
    excavator_attrs[:crew_onsite] = excavator_json["CrewOnsite"]

    self.create_excavator!(excavator_attrs)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  layout false
  skip_before_action :verify_authenticity_token
end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < Api::V1::BaseController
  def create
    json = json_param

    if json.present?
      Ticket.create!(original_json: json)
    else
      head 400
    end
  end

  private

  def json_param
    json_str = params[:json]

    if json_str.present?
      begin
        json = JSON.parse(json_str)
      rescue JSON::ParserError => e
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.order(created_at: :desc).paginate(page: params[:page] || 1, per_page: params[:per_page] || 20)
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date ? date.strftime("%m/%d/%Y") : date
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<div class="container">
  <% if @tickets.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Request number</th>
          <th>Sequence number</th>
          <th>Request type</th>
          <th>Response due date time</th>
          <th>Primary service area code</th>
          <th>Additional service area codes</th>
        </tr>
      </thead>
      <tbody>
        <% @tickets.each do |ticket| %>
          <tr>
            <td><%= link_to(ticket.id, ticket_path(ticket)) %></td>
            <td><%= ticket.request_number %></td>
            <td><%= ticket.sequence_number %></td>
            <td><%= ticket.request_type %></td>
            <td><%= format_date(ticket.response_due_date_time) %></td>
            <td><%= ticket.primary_service_area_code %></td>
            <td><%= (ticket.additional_service_area_codes || []).join(", ") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <%= will_paginate @tickets %>
    </div>
  <% else %>
    <div class="text-center">No tickets found</div>
  <% end %>
</div>

app/views/tickets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <table class="table">
        <tbody>
          <tr>
            <td>Request Number</td>
            <td><%= @ticket.request_number %></td>
          </tr>
          <tr>
            <td>Sequence Number</td>
            <td><%= @ticket.sequence_number %></td>
          </tr>
          <tr>
            <td>Request Type</td>
            <td><%= @ticket.request_type %></td>
          </tr>
          <tr>
            <td>Response Due Date Time</td>
            <td><%= format_date(@ticket.response_due_date_time) %></td>
          </tr>
          <tr>
            <td>Primary Service Area Code</td>
            <td><%= @ticket.primary_service_area_code %></td>
          </tr>
          <tr>
            <td>Additional Service Area Codes</td>
            <td><%= (@ticket.additional_service_area_codes || []).join(", ") %></td>
          </tr>
          <tr>
            <td>Company Name</td>
            <td><%= @ticket.excavator.company_name %></td>
          </tr>
          <tr>
            <td>Address</td>
            <td><%= @ticket.excavator.full_address %></td>
          </tr>
          <tr>
            <td>Crew Onsite</td>
            <td><%= @ticket.excavator.crew_onsite %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-sm-8">
      <div id="map" style="height:400px"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var wellKnownShape = <%= @ticket.well_known_shape.to_json.html_safe %>;

  function onMapLoaded() {
    if (wellKnownShape && wellKnownShape.points) {
      var center = calculateCenter(wellKnownShape.points);

      if (center && center.lat && center.lng) {
        var centerLatLng = new google.maps.LatLng(center.lat, center.lng);
        var map = new google.maps.Map(jQuery("#map")[0], {
          zoom: 8,
          center: centerLatLng
        });

        fitBounds(map, wellKnownShape.points);

        if (wellKnownShape.shape == "POLYGON") {
          var polygon = new google.maps.Polygon({
            paths: wellKnownShape.points,
            strokeColor: "#FF0000",
            strokeOpacity: 0.8,
            strokeWeight: 1,
            fillColor: "#FF0000",
            fillOpacity: 0.35
          });
          polygon.setMap(map);
        }
      }
    }
  }
</script>
<script type="text/javascript" src='//maps.googleapis.com/maps/api/js?callback=onMapLoaded' defer></script>